name: Test VRP Solutions

on: [pull_request]

jobs:
  test-solutions:
    runs-on: ubuntu-latest
    outputs:
      changed-dir: ${{ steps.set_changed_dir.outputs.changed-dir }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Important to fetch all history for git diff

    - name: Identify Changed Directories
      id: set_changed_dir
      run: |
        CHANGED_DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^Groups/' | cut -d'/' -f2 | uniq)
        echo "Changed directories: $CHANGED_DIRS"
        if [ -n "$CHANGED_DIRS" ]; then
          echo "CHANGED_DIRS=$CHANGED_DIRS" >> $GITHUB_ENV
        fi

    - name: Run tests on group's submission
      run: |
        if [ -z "${CHANGED_DIRS}" ]; then
          echo "No group directories have changed."
          exit 0
        fi
        IFS=' ' read -r -a DIR_ARRAY <<< "${CHANGED_DIRS}"
        for DIR in "${DIR_ARRAY[@]}"
        do
          python .github/run_tests.py Groups/$DIR
        done


